version: '3.9'
services:
  db:
    image: postgres:latest
    container_name: rinha-rust-db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=rinha
      - POSTGRES_DB=rinha
      - PGPORT=5433
    ports:
      - "5433:5433"   
    network_mode: host 
    command: 'postgres -c max_connections=1000 -c shared_buffers=96MB -c checkpoint_timeout=600 -c synchronous_commit=off -c fsync=off -c full_page_writes=off -c work_mem=16MB'
    volumes:
      - ./ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
      - type: tmpfs
        target: /var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '450MB' 
    healthcheck:
      test: ["CMD", "pg_isready", "--username", "rinha"]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 15s
      start_interval: 1s
  
  api01: &api
    image: rinha-rust-api    
    container_name: rinha-rust-api-1
    network_mode: host
    environment: &env
      DATABASE_URL: postgres://rinha:123@localhost:5433/rinha
      DATABASE_POOL: 250
      PORT: 3000
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '30MB'

  api02:
    <<: *api       
    container_name: rinha-rust-api-2
    environment:
      <<: *env
      PORT: 3001  

  nginx:
    image: nginx:latest
    container_name: rinha-rust-nginx
    network_mode: host
    volumes:
      - ./nginx-arm64.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02    
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '40MB'


